### ISSUE TITLE
laravel flash doesnt working after update laravel 5.4

### ISSUE THREAD

**Issue by dhanyn10** [laracasts/flash#106]
last night i'm updating my laravel project in version 5.4.
in the same version, before update several dependencies and other plugin, there's no problem with my flash message. but after that, the flash message is not showing anymore without any problem displayed in app debug. here's my ``composer.json`` files
```{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laracasts/flash": "^3.0",
        "laravel/framework": "5.4.*",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}```

**Comment by AlexanderPoellmann** [comment]
Have you updated to laracasts/flash v3 recently?

First of all you should clear your view cache: `php artisan view:clear`

Then, check if you published the old view templates to your project (from v2). Update them accordingly: https://github.com/laracasts/flash/blob/master/src/views/message.blade.php

**Comment by yyano** [comment]
I was corrected by this
`php artisan vendor:publish --provider="Laracasts\Flash\FlashServiceProvider" --force`
and 
`php artisan view:clear`

**Comment by dhanyn10** [comment]
thanks. i seems i've missed several things when installing flash. now this flash message worked fine. 😄
