### ISSUE TITLE
No close button

### ISSUE THREAD

**Issue by Ucer** [laracasts/flash#107]
I have see the flash message successful , but the is no `close button` on my screen。like this

**Comment by AbubakarWaryah** [comment]
You nee to add following library  into your views.
<script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

**Comment by rahulhaque** [comment]
Try chaining the `->importan()` method in your flash message.
Like `flash('Your Message')->important();`
