### ISSUE TITLE
Close button should appear when the message is NOT important

### ISSUE THREAD

**Issue by taka-oyama** [laracasts/flash#113]
`messsage.blade.php` renders the close button when the message['important'] is set to true but shouldn't it be the other way around?

```
@if ($message['important'])  // should be @if (! $message['important']) ?
    <button type="button"
            class="close"
            data-dismiss="alert"
            aria-hidden="true"
    >&times;</button>
@endif
```

**Comment by ruchern** [comment]
The current version is correct.

**Comment by taka-oyama** [comment]
I don't understand the intention. Can you elaborate?

**Comment by taka-oyama** [comment]
I watched the video for this and noticed that this code works in parallel with JS and the default behaviour was to let it fade out. Kinda hard to follow...
