### ISSUE TITLE
Flash message not working.

### ISSUE THREAD

**Issue by WhitneyOgutu** [laracasts/flash#126]
Here's what I have in my store function in my controller ..
```
` public function store(Request $request)
    {
       Job::create($request->all());
        flash('Job created successfuly!')->success();
        return redirect('home');
   
 }
`
```
And here's how I've referenced it in my view 

` <div class="container">
 @include('flash::message')
    <div class="row"> `

What could be the issue ?

**Comment by MartinAnt** [comment]
I am having the same issue with the exact same code. Did you find a solution ?

**Comment by WhitneyOgutu** [comment]
@MartinAnt Not quite ...
