### ISSUE TITLE
Is this package being maintained?

### ISSUE THREAD

**Issue by jeffreydwalter** [laracasts/flash#135]
I see a bunch of issues and PRs that are being neglected. I'd like to use this package, but don't want to invest in dead code. I'd be willing to consider inheriting it if so.

**Comment by ricardovigatti** [comment]
Well, last commit from seven months ago seems pretty reasonable for a package that old. I use it since 1.x versions and it stills useful.

**Comment by jeffreydwalter** [comment]
@ricardovigatti is it? I'm of the opinion that if a repo has a bunch of issues and PRs that have gone unanswered, the code base is probably dead and shouldn't be used.

**Comment by cannect** [comment]
+1

**Comment by JeffreyWay** [comment]
The package is maintained, but I neither have the time or desire to monitor it weekly. I check in a few times each year to bring it up to speed. It fully works.
