### ISSUE TITLE
Call to a member function update() on null when call App::setLocale('en') on Middleware

### ISSUE THREAD

**Issue by dsouksavatd** [laracasts/flash#142]
I got error message "Call to a member function update() on null" 
error on file vendor/laracasts/flash/src/Laracasts/Flash/FlashNotifier.php
protected function updateLastMessage($overrides = [])
{
   $this->messages->last()->update($overrides); <-- Errror here
   return $this;
}
when I try to add LocaleMiddleware which is execute App::setLocale('en'), but it working without issue when disable this middleware call
![screen shot 2019-01-18 at 16 03 21](https://user-images.githubusercontent.com/2195503/51376308-99914b80-1b3a-11e9-8be9-27a4609a275b.png)

**Comment by ourcoteam** [comment]
Did you find a solution for ?

**Comment by ourcoteam** [comment]
@dsouksavatd
