### ISSUE TITLE
Readme images missing

### ISSUE THREAD

**Issue by fhdalikhan** [laracasts/flash#146]
Below readme images are not showing

https://dl.dropboxusercontent.com/u/774859/GitHub-Repos/flash/message.png
https://dl.dropboxusercontent.com/u/774859/GitHub-Repos/flash/error.png
https://dl.dropboxusercontent.com/u/774859/GitHub-Repos/flash/overlay.png

**Comment by MercierCorentin** [comment]
Hey! Same issue as #133 ;)

**Comment by mikeerickson** [comment]
I have a feeling @JeffreyWay has stopped supporting this package as there has not been any movement in the past year or so, and the issues are "piling up"

There is an alternate package from @spatie which seems to be a good replacement

https://github.com/spatie/laravel-flash

**Comment by MercierCorentin** [comment]
I also have this feeling... 
@mikeerickson thanks for the alternate package!
