### ISSUE TITLE
TailwindCSS support

### ISSUE THREAD

**Issue by nauvalazhar** [laracasts/flash#155]
Hi,
currently, only available for the Bootstrap framework, is it available for the TailwindCSS framework?

Thank you for the helpful package!

**Comment by underthecocotree** [comment]
Hi,

I was working this out myself so I had a look and saw your issue.

I wrapped tailwindcss as a component using the bootstrap alert classes.  

You could go down the road of publishing the views and changing them around.
`php artisan vendor:publish --provider="Laracasts\Flash\FlashServiceProvider"`

From what I saw the bootstrap classes are based on the type of the message as 
`alert alert-{{ $message['level'] }}`.  
Reference: https://github.com/laracasts/flash/blob/77fe3a0f0ebf32c66d9c891782e3fa4b305df249/src/views/message.blade.php#L9

The type get's send form the [FlashNotifer.php.](https://github.com/laracasts/flash/blob/77fe3a0f0ebf32c66d9c891782e3fa4b305df249/src/Laracasts/Flash/FlashNotifier.php#L55)  That means it would need to send different class names to make it pure tailwindcss.

In a .scss file
```
// https://getbootstrap.com/docs/4.0/components/alerts/
// https://tailwindcss.com/components/alerts
.alert {
    @apply 
        border-t-4 
        rounded-b
        shadow-md 
        px-4 py-3;
    
    &.alert-success {
        @apply bg-teal-100 
            border-teal-500 
            text-teal-900;
    }

    &.alert-danger {
        @apply bg-red-100 
            border-red-500 
            text-red-900;
    }

    &.alert-warning {
        @apply bg-yellow-100 
            border-yellow-500 
            text-yellow-900;
    }
    
    &.alert-info {
        @apply bg-blue-100 
            border-blue-500 
            text-blue-900;
    }

    button.close {
        float: right;
    }
}
```

To view the results put this in a blade file
```
@php 
  flash('hello')->info(); 
  flash('hello')->warning(); 
  flash('hello')->success(); 
  flash('hello')->error(); 

  flash('hello')->info()->important(); 
  flash('hello')->warning()->important(); 
  flash('hello')->success()->important(); 
  flash('hello')->error()->important(); 
@endphp
```

It seems that the plugin has been built with bootstrap in mind. 

Let me know if you find a better way.  Hope this helps others out.

**Comment by josegus** [comment]
You can use your own css classes, or use the bootstrap naming convention with your own css generated tailwind classes.
