### ISSUE TITLE
No flash messages after redirect

### ISSUE THREAD

**Issue by Daniesy** [laracasts/flash#27]
Hey!
I have this code in a middleware

```
       Flash::error('You need to be authenticated as admin to access this page.');
       return redirect()->guest('auth/login');
```

Nothing happens on `auth/login` page. The rest works as intended.

**Comment by Daniesy** [comment]
This is how the session looks after redirect 
    array:6 [
      "_token" => "oCPeqs76n4dOjH6UiskZYKmwC8PxakIaA0UIjEAj"
      "_previous" => array:1
      "flash" => array:2
      "url" => array:1
      "login_82e5d2c56bdd0811318f0cf078b78bfc" => 1
      "flash_notification" => []
    ]

**Comment by lockncode** [comment]
@Daniesy Are you using App/Http/Requests\<something> in your controller for validation?  If so, unfortunately, it will never even get to that part if your controller method.

**Comment by EHLOVader** [comment]
I was having this issue when redirecting back to `/` which I used `guest` middleware on and redirects back to `/home` when logged in. 
The problem appears to be that the flash message is consumed between those redirects.

**Comment by blitzkriegcoding** [comment]
I've tried to show the flash messages, but It does not work in Laravel 5.2, although I've updated the file FlashServiceProvider.php and nothing... I've found time after time... Trying assertions of code with dd() function...

**Comment by steverobbins** [comment]
I'm experiencing this issue as well.

In a controller I have:

```
Flash::error('Your scan has been queued and will be processed shortly.');
return redirect($scan->url());
```

I'm using `@include('flash::message')` on all pages.  `var_dump(session('flash_notification'));` returns `NULL`.

It only seems to work if I `return view()`, i.e.

```
Flash::error('Sorry, the site you requested does not exist.');
return view('pages.scan');
```

will work.

@lockncode Can you explain what you mean by "using App/Http/Requests<something> in your controller for validation"?

Here is my entire controller, I don't think it's using any fancy validation or middleware that would cause this unexpected behavior.

```
<?php

namespace App\Http\Controllers;

use App\Scan;
use App\Site;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;

/**
 * Controller for site pages
 */
class SiteController extends Controller
{
    /**
     * Display new site scan form
     *
     * @param  Request $request
     * @return \Illuminate\View\View
     */
    public function getIndex(Request $request)
    {
        $url = $request->input('url');
        if ($url) {
            $site = Site::loadByUrl($url);
            $scan = $site->queueScan();
            if ($scan !== false) {
                Flash::error('Your scan has been queued and will be processed shortly.');
                return redirect($scan->url());
            } elseif ($scan = $site->pendingScan()) {
                Flash::error('A scan is already pending for this site.');
                return redirect($scan->url());
            }
            Flash::error('This site has reached it\'s scanning limit, but you can still view previous scans.');
            return redirect($site->url());
        }
        return view('pages.scan');
    }

    /**
     * Site detail page
     *
     * @param  Request      $request
     * @param  string       $siteIdentifier
     * @param  string|null  $scanIdentifier
     * @return \Illuminate\View\View
     */
    public function getSite(Request $request, $siteIdentifier, $scanIdentifier = null)
    {
        $site = Site::loadByIdentifier($siteIdentifier);
        if (!$site) {
            Flash::error('Sorry, the site you requested does not exist.');
            return view('pages.scan');
        }
        return view('pages.site.detail', [
            'site' => $site,
            'scan' => Scan::loadByIdentifier($scanIdentifier),
        ]);
    }
}
```

**Comment by blitzkriegcoding** [comment]
@steverobbins  There's a new form how Laravel 5.2 manages the sessions? I don't have much time for review the code throghoutly about the session... I only did a downgrade of version from 5.2 to 5.1 and works fine... I'm following a tutorial of laravel but the version 5.2 had not been released yet at that date... I wrote to the author, but he doesn't know nothing about this issue...

**Comment by EHLOVader** [comment]
Try adding the `web` middleware on your routes. or ensure the web middleware group contains the `StartSession` middleware.

via  https://laracasts.com/discuss/channels/laravel/auth-session-killed-after-redirect-laravel-52/replies/124991

more on middleware groups here https://laravel.com/docs/5.2/middleware#middleware-groups

Good luck!

**Comment by steverobbins** [comment]
Thanks @EHLOVader, that resolved this issue for me.

**Comment by ronaldrios** [comment]
Thanks @EHLOVader, it did work for me too.

**Comment by ckwong** [comment]
I use laravel 5.2, found "No flash messages after redirect" same problem, and check web middleware on routes completed, any problem ?

**Comment by EHLOVader** [comment]
So you have the web middleware set globally? or in a group which is wrapping the relevant routes?

**Comment by stueynet** [comment]
I can confirm the same issue since upgrading. Only when I return a view do I get the flash message. If I do a redirect() I get nada. I am using web middleware as well.

**Comment by hamedmohammadi** [comment]
i still have the problem even after setting web middleware to my routes group

**Comment by thawy-dev** [comment]
i have the same problem too

**Comment by Aaronhdez** [comment]
Same problem here, web middleware set globally but the message isn't still work after redirecting process.

**Comment by thawy-dev** [comment]
@Aaronhdez what version Laravel you have?

**Comment by Aaronhdez** [comment]
@thawy-dev 5.2.29

**Comment by thawy-dev** [comment]
@Aaronhdez you not need to use "web" middleware in the laravel 5.2.
Try to remove it from your routes.php file. This way helps me

**Comment by stojankukrika** [comment]
I do not have middleware in routes file but also do not work. Please @JeffreyWay fix it.

**Comment by cent040** [comment]
thanks @Aaronhdez  that resolved this issue for me. while removing web middleware from routes.

**Comment by thawy-dev** [comment]
@cent040 Welcome!

**Comment by chaot1x** [comment]
This is what I did to get flash message to appear when there is an redirect

Put this where 2nd redirect happens
```
if(session()->has('flash_notification.message')) {
   flash(session()->get('flash_notification.message'), session()->get('flash_notification.level'));
}
```
Note that it works only with latest update

**Comment by sunscreem** [comment]
For what its worth I've worked around this by "manually" adding the notification to the session data instead of using the helper. It seems to persist that way:

` session(['flash_notification'=>['message'=>"Your message here",
                                        'level'=>"success"]]);`

HOWEVER - It will now also stick around in the session indefinitely so .. in the view I've snuck this in to be 100% sure the data is cleared. 

`@php session()->forget('flash_notification') @endphp`

Its messy - but it means I can continue to use this package when with or without the redirect issue.

**Comment by razvaniacob** [comment]
So there's still no solution to this problem yet? I'm using Laravel 5.3 and the session is not set.

**Comment by vernard** [comment]
@razvaniacob Me too. The `StartSession` middleware is added on the `web` middleware group too. Not sure where the problem is.

**Comment by rmff** [comment]
Hi,
@JeffreyWay any solution for L5.3?  
Tks

**Comment by justin-cook** [comment]
@rmff If you upgraded to 5.3 from an earlier version, make sure you commented out the start session in the Kernel.php.
