### ISSUE TITLE
When message text contains accents it is ignored

### ISSUE THREAD

**Issue by yzaroui** [laracasts/flash#30]
After saving an article I used

Flash::success("Article enregistré.");
return redirect('/admin/articles');

I get the message div without any text.

If I replace the é with e, I get the message.

**Comment by kkiernan** [comment]
Did you ever figure this one out? I haven't had any problems with characters with accents.

**Comment by farhanwazir** [comment]
Same problem i'm facing.

**Comment by farhanwazir** [comment]
**Problem is resolved by changed file encoding to ISO-8859-1.** For new bee's its not meta tag, change it from your editor.

Actually, when you need to use sessions with Latin-based languages support then you should encode your output file encoding to ISO-8859-1. UTF-8 and ANSI will not support accents.
