### ISSUE TITLE
Flash reappearing on back navigation

### ISSUE THREAD

**Issue by opheliadesign** [laracasts/flash#32]
I've noticed in two separate projects that a Flash Overlay message will appear numerous times while using the Back button. For example, a `flash::overlay("User Saved")` followed by a `redirect()->route('users.index')` will show the Overlay message as expected. But if I go to another page and then click on the Back button to return to `users.index`, the Overlay appears once again (and subsequent times if the behavior is repeated).

Not sure if this is a bug or if I am missing something. In other words, the overlay seems to be stuck on the page that the user was directed to unless they visit that page again directly or reload it, not using the Back button.

**Comment by opheliadesign** [comment]
Any ideas on how to prevent this?  It's very misleading when users navigate the site.

**Comment by mblander** [comment]
Hi opheliadesign, I think I am having the same problems with using: Flash::info('message') on a form. The message is displayed correct but after clicking a link in my menu: href="{{ url('/') }}" the message will still show.

Did you find a way to handle the problem?

**Comment by Twijnand** [comment]
same problem here, anyone?

**Comment by razamehdi-vteams** [comment]
@Twijnand @mblander @opheliadesign Try this one, hopefully this works:
```
@if (Session::has('flash_notification.message'))
    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

        {{ Session::get('flash_notification.message') }}
    </div>
 {{ Session::forget('flash_notification.message') }}
@endif
```

**Comment by llhilton** [comment]
I had a similar issue, where the flash message would sometimes linger, although not always. It looks like @razamehdi-vteams will work for me. Thanks!

**Comment by sroutier** [comment]
Same issue, notifications appear twice. @razamehdi-vteams provided an easy fix. Thanks.
/s

**Comment by JeffreyWay** [comment]
This is because of browser caching. Not sure we can do anything about it.
