### ISSUE TITLE
I would like see fixed the lang

### ISSUE THREAD

**Issue by socieboy** [laracasts/flash#35]
Hi Jefrey I have using the Flash package and It help me a lot, I'm hispanic and most of my projects I write in spanish, It's not a big issue to change the button Close to Cerrar in spanish for the modal, but I have to go to the vendor directory all the time to change it, I would like to see lang file in your package or when we change the locate also changes the overlay modal.

Thank you!

**Comment by MichealMi** [comment]
Do `php artisan vendor:publish` and then edit the views in your "resources/views/flash" folder. This should fix your problem.

**Comment by jouva** [comment]
@LukasMa While this is true, an easier and less invasive solution would be using language files. If a modification around this is made down the line, this change will need to be remade with the update. With language files, an "es" version of the language file could be created by the requester and will be compatible with all future updates

**Comment by LukasMa** [comment]
@jouva Yes, language files are a far better solution! But I think a quick and dirty method to do some changes is to modifiy the views in the resources folder. The source files aren't touched by this.

**Comment by JeffreyWay** [comment]
I'd rather not maintain language files, so best to publish the templates and maintain yourself.
