### ISSUE TITLE
Blank page with Laravel 5.1-dev

### ISSUE THREAD

**Issue by virtous** [laracasts/flash#36]
Hey there! 
Just wanted to post a quick note on the issue I'm currently having when using flash with Laravel Framework version 5.1-dev

Whenever I run composer update I get the following.
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing laracasts/flash (1.3.3)
    Loading from cache

Writing lock file
Generating autoload files
Script php artisan clear-compiled handling the post-update-cmd event returned with an error
                 
  [RuntimeException]  
  Error Output:       
                      
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

I followed the installation instructions given in the docs (adding the service provider and alias), when I reload the page all I get is a blank page.

**Comment by mpmurph** [comment]
Hi Jeffrey - I am receiving the same error ("Script php artisan clear-compiled handling the post-update-cmd event returned with an error") when I run 'composer require' with Laravel v5.1.15. Is 'flash' not updated for 5.1, or is there a problem at my end that I am missing? Thanks!

**Comment by mhnrcjgs** [comment]
I got it install without any error. 

php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing laracasts/flash (1.3.3)
    Downloading: 100%

Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader

**Comment by mpmurph** [comment]
@mhnrcjgs I'm afraid the install is still not working for me... I keep getting the following:

```
Using version ^1.3 for laracasts/flash
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing laracasts/flash (1.3.3)
    Downloading: 100%         

Writing lock file
Generating autoload files
> php artisan optimize
Script php artisan optimize handling the post-update-cmd event returned with an error
                      
  [RuntimeException]  
  Error Output:       
```     

Once I had installed the package, I can no longer run 'php artisan' and 'composer remove laracasts/flash' doesn't work - I get the same error as above. In order to get everything working again, I have to manually delete laracasts/flash from both composer.json and composer.lock.

Not sure what the problem is?

**Comment by laracasts** [comment]
Was fixed a while back.
