### ISSUE TITLE
Allow for line break in message

### ISSUE THREAD

**Issue by lipkau** [laracasts/flash#43]
I would suggest switching to `{!! Session::get('flash_notification.message') !!}` in _/vendor/laracasts/flash/src/views/message.blade.php_ to allow html (useful for `<br>`)

**Comment by JoshMountain** [comment]
Agreed, html support would be nice for things like links in notifications as well.

**Comment by canfiax** [comment]
+1 - I would like to add some HTML as well. I.e anchor links.

**Comment by asad777** [comment]
agree +1

**Comment by JeffreyWay** [comment]
PR?

**Comment by lipkau** [comment]
PR #49
thx imknight

**Comment by bretto36** [comment]
This can be closed
