### ISSUE TITLE
flash_notification.important not considered in view

### ISSUE THREAD

**Issue by lipkau** [laracasts/flash#44]
Current partial _/vendor/laracasts/flash/src/views/message.blade.php_ does not consider the `->important()` method.
I suggest adding it as class to the alert:
`<div class="alert alert-{{ Session::get('flash_notification.level') }} {{ Session::has('flash_notification.important') ? 'alert-important' : '' }}">`

**Comment by shaneparsons** [comment]
@lipkau Good call! I created a pull request with your suggestion. https://github.com/laracasts/flash/pull/46
