### ISSUE TITLE
[Proposal] Multiple Messages

### ISSUE THREAD

**Issue by ax3lst** [laracasts/flash#6]
Like mentioned here: #5, it would be very helpful that the package displays multiple flash messages.

The messages could be sorted by importance, so this could be a possible display order:
1. The error messages
2. The warning messages
3. The success messages
4. The info messages

What do you think?

**Comment by RyanThompson** [comment]
In my opinion the messages would not be pushed together but kept in their own array / collections. It should be up to the dev to separate the "types".

**Comment by TheTechnoMan** [comment]
Any updates for this @laracasts @JeffreyWay ? I have to agree that this would be very useful, sometimes you need to flash more then one message at one request.

Thank you very much!

**Comment by judgej** [comment]
In my mind, multiple messages is an essential pre-requisite for any kind of flash messaging package. It is kind of broken functionality without it, if only one message of N messages generated get to be viewed the user, the rest simply being discarded.

**Comment by jklein** [comment]
:+1: 

Without multiple message support this package is pretty much useless for us unfortunately.

**Comment by RyanThompson** [comment]
You guys can just do a simple solution like this too: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Message/MessageBag.php

I prefer this over flash anyways. When you flash messages, let's say in a redirecting authentication process for instance, flash messages get lost. This will push into and pull out of session so they are more sticky!

**Comment by judgej** [comment]
I am giving this package a try:

https://github.com/edvinaskrucas/notification

So far, it's working out well. It feels kind of different flashing the messages before a redirect, instead of doing it as a part of the redirect as so many tutorials suggest, e.g. `->withFlash(...)` but it also feels right.

I would still send errors for form items the usual route though, `->withErrors(...)`, as the way those message bags work are fairly well defined and *do* handle multiple messages per form item already.

**Comment by EHLOVader** [comment]
:+1:

**Comment by vedmant** [comment]
:+1: I agree, without possibility to add several messages this package is not helpful!

**Comment by canfiax** [comment]
+1 - multiple flash messages is really needed.

**Comment by mydnic** [comment]
Someone should fork this package and start maintaining it, because I doubt @JeffreyWay has time to do it

**Comment by judgej** [comment]
Just grabbing *one* message from bags of messages seems to be the "laravel way". All the docs and all the guides I've seen use `->first()` to get messages everywhere. As soon as I see that, my thought is always, "but what about the rest"? I don't know where this idea that only the first message is ever needed, but it pervades all things Laravel like a virus.

**Comment by judgej** [comment]
@mydnic if everything https://github.com/edvinaskrucas/notification can do were merged in with it, we would have a great package. I use "notification" a lot for multiple page-level messages, but then also need to check `$errors` in the page layout template for any messages with a key of "0" and throw those in too (they will be errors that are *not* tied to a specific form item through the item name as a key).

**Comment by mydnic** [comment]
@judgej I will try this package then :)
thanks

**Comment by judgej** [comment]
This is at the top of my page to display all errors and messages:

~~~blade
            {{-- Show notifications package messages first --}}
            {!! Notification::showAll() !!}

            @if ($errors->any())
                {{-- Display any generic error messages here - those that are not tied to form fields. --}}
                @if ($messages = $errors->get(0, ':message'))
                    @foreach($messages as $message)
                        <div class="alert alert-danger alert-block">
                            {{ $message }}
                        </div>
                    @endforeach
                @endif
            @endif
~~~

It's quick and dirty, but doesn't miss any page-level messages or errors.

**Comment by EliasZ** [comment]
bump @JeffreyWay

Why not set messages & levels in `flash_notification.message` & `flash_notification.level` session flash storage as an array? Then in the view, iterate over them. Would be the simplest fix. The API will remain backwards compatible, only the (base) view requires an update.

**Comment by nelson6e65** [comment]
:+1:

**Comment by diegoalmesp** [comment]
+1

**Comment by flashek** [comment]
+1

**Comment by apocalyarts** [comment]
+1

**Comment by tudor2004** [comment]
+1

**Comment by vstruhar** [comment]
+1

**Comment by Hytii** [comment]
+1

**Comment by standaniels** [comment]
You can use my fork which supports multiple flash messages.
https://github.com/standaniels/flash

**Comment by PatrikValkovic** [comment]
I tried to rewrite original sources a bit, here is result of my effort.
https://packagist.org/packages/valkovic/flash

**Comment by JeffreyWay** [comment]
Added. Better late than never. :)

**Comment by nowak-ninja** [comment]
Yeah :) Thx

**Comment by nelson6e65** [comment]
Thanks! I'll try 😁
