### ISSUE TITLE
Lumen compatibility ?

### ISSUE THREAD

**Issue by Ifnot** [laracasts/flash#62]
Hello,

I tried to use `laracasts/flash` on lumen `5.x` and i could not get it working, here is the exception :

    Unresolvable dependency resolving [Parameter #0 [ <required> $name ]] in class Illuminate\Session\Store

It looks the `Illuminate\Session\Store` IoC resolution of the [LaravelSessionStore __constructor()](https://github.com/laracasts/flash/blob/master/src/Laracasts/Flash/LaravelSessionStore.php#L15) fails.

Maybe we can do a LumenSessionStore ? Is it planned ?

Thanks :)

**Comment by srmklive** [comment]
There is absolutely no need to add it in my opinion to add it to Lumen. Why do you want to add it to Lumen?

**Comment by Ifnot** [comment]
Hi,

Maybe for making a lightweight application using flash notifications ? :)

Lumen is not designed only for API, it handle well blade, sessions, eloquent and facade.

Dont you agree ?

**Comment by srmklive** [comment]
I agree, but what is the point of using a micro framework then? Why don't you use Laravel instead. Taylor Otwell himself discourages use of blade views, sessions etc in Lumen, as there is absolutely no need for it. 

If you are using these features in Lumen, then this absolutely defeats the purpose of a micro-framework itself.

**Comment by Ifnot** [comment]
Thanks for your opinion.

As Taylor discourages the use of these features, they are however implemented. This comes to our case here, as it is may be not a "best practice" to do an interface with Lumen, is it a bad thing to make it compatible ? Some people could need this in some projects, and this is called flexibility for all use cases :)

I think a micro-framework can be used for a small project with light complexity but should not restrict technologies. As it can be used for a simple 4 pages private interface using blade + session.
