### ISSUE TITLE
typo in https://github.com/laracasts/flash installation instructions

### ISSUE THREAD

**Issue by superwebdeveloper** [laracasts/flash#68]
In your installation instructions on https://github.com/laracasts/flash there is a typo. 

```
'aliases' => [
    'Flash' => Laracasts\Flash\Flash:class,
];
```

should be double colon as in: 

```
'aliases' => [
    'Flash' => Laracasts\Flash\Flash::class,
];
```
its a small issue, but documentation matters as much as everything else. Dont vex the user!

**Comment by JeffreyWay** [comment]
Fixed.
