### ISSUE TITLE
Default templates do not escape messages

### ISSUE THREAD

**Issue by andyvenus** [laracasts/flash#75]
The default templates included with this package do not escape Flash messages: https://github.com/laracasts/flash/blob/master/src/views/message.blade.php#L15

While this is understandable as developers may want to flash HTML messages, it is not documented as the default behaviour. 

In the docs example the message is escaped:

    @if (Session::has('flash_notification.message'))
        <div class="alert alert-{{ Session::get('flash_notification.level') }}">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    
            {{ Session::get('flash_notification.message') }}
        </div>
    @endif

This strongly implies that the included templates are also escaped although they are not.

I feel it would be safest to default to escaping the messages and let users create custom templates if they want to use HTML.

**Comment by JeffreyWay** [comment]
You're in full control over the flash messages, so I think it's fine.

**Comment by andyvenus** [comment]
We have control of the templates, yes. We do now have our templates escape the messages.

Maybe we should have checked the included templates, and that's on us. But because the message was escaped in the documentation we assumed the included templates would do the same. During penetration testing of our project we then found out this wasn't the case.

So all I'm calling for is at least a little warning so nobody falls into the same trap as us.

**Comment by CountZero1981** [comment]
We experienced the same problem on our site.
