### ISSUE TITLE
Flashes disappearing after Redirect

### ISSUE THREAD

**Issue by cat24max** [laracasts/flash#88]
This was mentioned in a previous ticket.
If I do
```
flash(string);
return back(); //Or to a specific URL
```
There will not be any flash message. However, if I flash before I return a view it works like a charm.

Strangely, this has worked like 2 days ago without any relevant change to the code.

I am using Laravel 5.4 with AdminLTE.

**Comment by iVanilla** [comment]
Same issue for me.

**Comment by ryantology** [comment]
Had a similar issue. It was caused by upgrading to 5.4 with the new middleware groups. If you have duplicate middleware included ie.:
`\Illuminate\Session\Middleware\StartSession::class,`
This will cause the sessions for flash messages to fail.
