### ISSUE TITLE
Is this project "dead"?

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/flash#90]
It seems that either this project is "dead" or there is something out there which replaces it as there has not been any activity in quite some time?

@JeffreyWay would you mind giving some insight?   If it is "dead" from your perspective, I am willing to take over and keep it moving forward.

Or, if there is something "better" which replaces it, please let me know :-)

**Comment by mknooihuisen** [comment]
I'm also happy to help keep it going. :)

**Comment by JeffreyWay** [comment]
It's not dead.
