### ISSUE TITLE
Please add another collaborator or two to this project.

### ISSUE THREAD

**Issue by jeff-h** [laracasts/flash#92]
@JeffreyWay — thanks for sharing this code. I, and [![Total Downloads](https://poser.pugx.org/laracasts/flash/downloads)](https://packagist.org/packages/laracasts/flash) others appreciate it! :)

However, it's always a bit frustrating to see some good Pull Requests stagnating (multiple messages, translatable UI etc etc).

I'm seeing that numerous forks are emerging, most with just one feature added, and none likely to have much forward maintenance. This `laracasts/flash` repo really should be the canonical source for the latest and greatest version. 

I'm therefore asking whether you'd consider adding one or more collaborators on this project — people with write access who can merge the PRs and keep the project alive without requiring constant energy from you.

Thoughts?

**Comment by ruchern** [comment]
Yes please. I see this project having a lot more potential that just this.

**Comment by mikeerickson** [comment]
Hey gang 

I am more than will to take on contributor role, but seems Jeffrey is not to active / responsive to our request.  

I will contact him directly and get some dialog going

Stay tuned :)

**Comment by JeffreyWay** [comment]
I'm working on this repo a bit today. There's not much work that needs to be done.
