### ISSUE TITLE
Plans for UIKit integration?

### ISSUE THREAD

**Issue by ruchern** [laracasts/flash#94]
Apparently the package is now built on Bootstrap. It would be nice if there is some ways to use UIKit as the styling.

**Comment by mikeerickson** [comment]
@ruchern How do you mean?  What changes would you like to see that makes it integrate with UIKit?

**Comment by ruchern** [comment]
@mikeerickson For example, now it is coded with Bootstrap

For example:
```html
<div class="alert alert-primary">
</div>
```

UIKit:
```html
<div uk-alert>
    <div class="uk-alert-primary"></div>
</div>
```

**Comment by mikeerickson** [comment]
@ruchern you can easily change the template and make it work as you wish? Is UIKit actually in production from Bootstrap?  I thought this was in BS4 which is *still* technically in beta.

**Comment by ruchern** [comment]
@mikeerickson UIKit 3 is in beta, close to release and Bootstrap 4 is still in Alpha based on their website.

Okay, I will just edit the files directly from the vendor folder to integrate UIKit for my use. Thanks!

**Comment by mikeerickson** [comment]
@ruchern fwiw, doesn't seem this project is maintained by Jeffrey.  There have been many attempts to get his feedback, any many have offered to help (myself included) but it has gone silent 

I think updated the template yourself will ge you to the end game quicker.  This is the approach I have taken myself for my projects that use this package.

**Comment by JeffreyWay** [comment]
Just manually update the template.

**Comment by ruchern** [comment]
@JeffreyWay Alright. Thanks.
