### ISSUE TITLE
Upgrading from v2 to v3 copies old flash message views instead of new

### ISSUE THREAD

**Issue by jaminscript** [laracasts/flash#95]
I upgraded from version 2 to version 3 and ran:

`php artisan vendor:publish --provider="Laracasts\Flash\FlashServiceProvider"`

and received the following message:

`Copied Directory [\vendor\laracasts\flash\src\views] To [\resources\views\vendor\flash]`

However, the contents of that folder contains old code that isn't compatible with the new v3.

Did I just fail to use composer correctly, or is this something that can be addressed?

My steps (with v2 still installed):

`composer require laracasts/flash`

produces:

`Updating laracasts/flash (2.0.1 => 3.0.0): Downloading (100%)`

Then:

`php artisan vendor:publish --provider="Laracasts\Flash\FlashServiceProvider"`

produces:

`Copied Directory [\vendor\laracasts\flash\src\views] To [\resources\views\vendor\flash]`

Thoughts?

**Comment by jaminscript** [comment]
Manually copying the new `message.blade.php` code from this repo and overriding the old code makes everything work again, but of course that's not how it's supposed to be done.

**Comment by JeffreyWay** [comment]
Hmm, seems like a composer update issue. Going to close for now, since I'm pretty sure the latest update includes the new templates.
